### ISSUE TITLE
details of n_gpu and batch size 

### ISSUE THREAD

**Issue by Leonmel** [fcakyon/small-object-detection-benchmark#8]
Hi @fcakyon, thanks for your sharing this impressive project!

I would like to know the specific settings of `BATCH_MULTIPLIER` and `n_gpus` and `lr` in your configs, and I am confused by the current comments:
```
BATCH_MULTIPLIER = 16
...
samples_per_gpu=2 * BATCH_MULTIPLIER,
...
# optimizer
# default 8 gpu
# /8 for 1 gpu
optimizer = dict(
    lr=0.01 / 8 * BATCH_MULTIPLIER * LR_MULTIPLIER, paramwise_cfg=dict(bias_lr_mult=2.0, bias_decay_mult=0.0)
)
```
Is this configuration for single gpu? Do I need to modify `BATCH_MULTIPLIER` or anything else if I change it to 8 gpus.

It seems like I cannot train with such a large batch size even with 32GB GPU memory.

Hope for your reply.

**Comment by fcakyon** [comment]
This calculation is for a single GPU. If you don't have enough vram then you should lower the `BATCH_MULTIPLIER` value and `lr` will be scaled automatically.

If you will train with more than 1 GPU then multiply with number of GPUs as `lr=0.01 / 8 * BATCH_MULTIPLIER * LR_MULTIPLIER * NUM_GPUS`

**Comment by Leonmel** [comment]
Thank you for your prompt reply!
btw, could you tell me the meaning of `num_cls=60` in `TAGS`

**Comment by fcakyon** [comment]
`TAGS` are optional and can be used while logging to experiment trackers (wandb/neptune/comet).

`num_cls=60` means there a re 60 classes in the dataset.

**Comment by Leonmel** [comment]
Thanks a lot
